[build]
command = "npm run build"
functions = "functions"
publish = "_site"
base = "site"

[[redirects]]
from = "/userlibs/:slug/"
to = "/.netlify/builders/userlibs"
status = 200
force = true
_generated_by_eleventy_serverless = "userlibs"

[[redirects]]
from = "/test/:slug/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
