[build]
command = "npm run build"
functions = "functions"
publish = "_site"
base = "site"

[functions.userlibs]
external_node_modules = [ "@11ty/eleventy", "@11ty/dependency-tree", "pug-filters" ]
included_files = [ "/functions/userlibs/**/*", "/functions/userlibs/**" ]
