[build]
command = "npm run build"
functions = "functions"
publish = "_site"
base = "site"

[functions.userlibs]
node_bundler = "esbuild"
external_node_modules = ["@11ty/eleventy", "@11ty/dependency-tree"]
included_files = [
    "/netlify/functions/userlibs/**/*",
]

[[redirects]]
from = "/userlibs/:slug/"
to = "/.netlify/functions/userlibs"
status = 200
force = true
_generated_by_eleventy_serverless = "userlibs"

[[redirects]]
from = "/userlibs/:slug/"
to = "/.netlify/builders/userlibs"
status = 200
force = true
_generated_by_eleventy_serverless = "userlibs"

[[redirects]]
from = "/test/:slug/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
