[build]
command = "npm run build"
functions = "functions"
publish = "_site"
base = "site"

[functions.userlibs]
external_node_modules = [ "@11ty/eleventy", "@11ty/dependency-tree", "pug-filters" ]
included_files = [
  "**/functions/userlibs/**/*",
  "**/functions/userlibs/**"
]

[[redirects]]
from = "/userlibs/:slug/"
to = "/.netlify/builders/userlibs"
status = 200
force = true
_generated_by_eleventy_serverless = "userlibs"


[[redirects]]
from = "./functions/userlibs"
to = "/.netlify/builders/userlibs"
status = 200
force = true
_generated_by_eleventy_serverless = "userlibs"


